services:
  - type: web
    name: django-blog
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    autoDeploy: true

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free