services:
  - type: web
    name: your-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd mysite && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/mysite
      sizeGB: 1
    autoDeploy: true

databases:
  - name: django-blog-db
    databaseName: django_blog
    plan: free
    ipAllowList: [] # Разрешить доступ только с сервисов Render