services:
  - type: web
    plan: free
    name: your-app-name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application --bind=0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free