services:
  - type: web
    name: django-blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog_user 