services:
  - type: web
    name: sity-lvo8
    env: python
    buildCommand: sh build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: DATABASE_NAME
        value: django_blog_7f9a
      - key: DATABASE_USER
        value: django_blog_7f9a_user
      - key: DATABASE_PASSWORD
        value: qNKOalXZlLxzA7rlrYmbkN96ZJ6oHbbE
      - key: DATABASE_HOST
        value: dpg-csrl8f1u0jms7392hlrg-a.oregon-postgres.render.com
      - key: DATABASE_PORT
        value: "5432"
  
  - type: cron
    name: keep-alive
    schedule: "*/2 * * * *"
    httpMethod: GET
    url: https://sity-lvo8.onrender.com/health/

databases:
  - name: django-blog-db
    databaseName: django_blog
    plan: free
    postgresMajorVersion: 15