services:
  - type: web
    name: sity-lvo8
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py create_superuser
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /health/
    
  - type: cron
    name: keep-alive
    schedule: "* * * * *"
    httpMethod: GET
    url: https://sity-lvo8.onrender.com/health/

databases:
  - name: django-blog-db
    databaseName: django_blog
    plan: free
    ipAllowList: []