services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p staticfiles
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: STATIC_ROOT
        value: staticfiles
      - key: DISABLE_COLLECTSTATIC
        value: 0

databases:
  - name: django-blog-db
    plan: free
    databaseName: django_blog
    ipAllowList: []