services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      ls -la && pwd && cd mysite && PYTHONPATH=/opt/render/project/src/mysite gunicorn --bind=0.0.0.0:$PORT config.wsgi:application --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: sitebeta.onrender.com,localhost,127.0.0.1,.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src/mysite
      - key: PYTHONUNBUFFERED
        value: "1"
    staticPublishPath: mysite/staticfiles

databases:
  - name: django-blog-db
    plan: free