services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      # Устанавливаем зависимости
      pip install -r requirements.txt
      # Проверяем структуру проекта
      echo "Project structure before collectstatic:"
      ls -la
      # Собираем статику и делаем миграции
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      # Создаем символическую ссылку на config в корне проекта
      ln -s /opt/render/project/src/config /opt/render/project/src/venv/lib/python3.11/site-packages/config
      # Проверяем Python path и структуру
      echo "PYTHONPATH=$PYTHONPATH"
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      # Запускаем с явным указанием путей
      PYTHONPATH=/opt/render/project/src:/opt/render/project/src/venv/lib/python3.11/site-packages \
      DJANGO_SETTINGS_MODULE=config.settings \
      gunicorn config.wsgi:application --bind=0.0.0.0:$PORT --chdir=/opt/render/project/src
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/venv/lib/python3.11/site-packages

databases:
  - name: django-blog-db
    plan: free