services:
  - type: web
    name: sitebeta
    env: python
    buildCommand: ./build.sh
    startCommand: >
      cd mysite && 
      PYTHONPATH=$PYTHONPATH:/opt/render/project/src/mysite 
      gunicorn --bind 0.0.0.0:10000 config.wsgi:application
    python_version: 3.11.10
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/mysite

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free 