services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p staticfiles media
    startCommand: |
      cd /opt/render/project/src && \
      PYTHONPATH=/opt/render/project/src gunicorn --chdir /opt/render/project/src config.wsgi:application --bind=0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    buildFilter:
      paths:
      - manage.py
      - config/**
      - blog/**
      - templates/**
      - static/**
      - requirements.txt

databases:
  - name: django-blog-db
    plan: free