services:
  - type: web
    name: sity-lvo8
    env: python
    buildCommand: sh build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: postgres://django_blog_7f9a_user:qNKOalXZlLxzA7rlrYmbkN96ZJ6oHbbE@dpg-csrl8f1u0jms7392hlrg-a.oregon-postgres.render.com/django_blog_7f9a
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PGHOST
        value: dpg-csrl8f1u0jms7392hlrg-a.oregon-postgres.render.com
      - key: PGPORT
        value: "5432"
      - key: PGUSER
        value: django_blog_7f9a_user
      - key: PGDATABASE
        value: django_blog_7f9a
  
  - type: cron
    name: keep-alive
    schedule: "*/2 * * * *"
    httpMethod: GET
    url: https://sity-lvo8.onrender.com/health/

databases:
  - name: django-blog-db
    databaseName: django_blog
    plan: free
    postgresMajorVersion: 15