services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      mkdir -p staticfiles
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: STATIC_URL
        value: /static/
      - key: STATIC_ROOT
        value: staticfiles
      - key: MEDIA_URL
        value: /media/
      - key: MEDIA_ROOT
        value: media
      - key: PORT
        value: 8000
      - key: DISABLE_COLLECTSTATIC
        value: 0
    staticPublishPath: ./staticfiles
    routes:
      - type: rewrite
        source: /static/*
        destination: /staticfiles/*

databases:
  - name: django-blog-db
    plan: free
    databaseName: django_blog
    ipAllowList: []