services:
  - type: web
    plan: free
    name: your-app-name
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application --bind=0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONPATH
        value: .
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free