services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      cd /opt/render/project/src && \
      PYTHONPATH=/opt/render/project/src \
      gunicorn --chdir /opt/render/project/src config.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: django-blog-db
    plan: free