services:
  - type: web
    name: sitebeta
    env: python
    buildCommand: ./build.sh
    startCommand: >
      cd mysite && 
      gunicorn config.wsgi:application 
      --bind=0.0.0.0:$PORT 
      --workers=4 
      --log-file=-
    python_version: 3.11.10
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/mysite
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: STATIC_ROOT
        value: /opt/render/project/src/mysite/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_ROOT
        value: /opt/render/project/src/mysite/media
      - key: MEDIA_URL
        value: /media/

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free 