services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p staticfiles media
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src
      python manage.py collectstatic --noinput || true
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src
      gunicorn config.wsgi:application --bind=0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
    buildFilter:
      paths:
      - manage.py
      - config/**
      - blog/**
      - templates/**
      - static/**
      - requirements.txt

databases:
  - name: django-blog-db
    plan: free