services:
  - type: web
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind=0.0.0.0:$PORT --chdir /opt/render/project/src"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog
    plan: free