services:
  - type: web
    name: django-blog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p staticfiles media
    startCommand: |
      cd /opt/render/project/src && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      gunicorn --chdir /opt/render/project/src --pythonpath . wsgi:application --bind=0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

databases:
  - name: django-blog-db
    plan: free