services:
  - type: web
    name: sity-lvo8
    env: python
    buildCommand: sh build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://django_blog_7f9a_user:qNKOalXZlLxzA7rlrYmbkN96ZJ6oHbbE@dpg-csrl8f1u0jms7392hlrg-a/django_blog_7f9a
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: django-blog-db
    databaseName: django_blog
    plan: free
    postgresMajorVersion: 15