# Generated by Django 5.1.3 on 2024-11-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_invitecode_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': 'Код приглашения', 'verbose_name_plural': 'Коды риглашения'},
        ),
    ]
