# Generated by Django 5.1.3 on 2024-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='page_name',
            field=models.CharField(choices=[('contacts', 'Страница контактов'), ('create_post', 'Создание постов')], max_length=100, unique=True),
        ),
    ]
