# Generated by Django 5.1.3 on 2024-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_posts_count',
            field=models.IntegerField(db_column='posts_count', default=0),
        ),
    ]
