# Generated by Django 5.1.3 on 2024-11-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile_is_blocked'),
        ('blog', '0007_alter_post_content'),
    ]

    operations = [
    ]
