# Generated by Django 5.1.3 on 2024-11-10 08:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_invitecode_options_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': 'Код приглашения', 'verbose_name_plural': 'Коды пиглашения'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
