# Generated by Django 4.2.3 on 2025-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['title'], 'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(help_text="Каждая строка должна начинаться с 'say ' или '/b '.", verbose_name='Содержание лекции'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
