# Generated by Django 4.2.3 on 2025-06-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_lecture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttemplate',
            name='category_new_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_text_templates', to='blog.category'),
        ),
    ]
