# Generated by Django 4.2.3 on 2025-06-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_texttemplate_category_new_fk'),
    ]

    operations = [
    ]
