# Generated by Django 4.2.3 on 2025-06-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20250617_1933'),
    ]

    operations = [
    ]
