# Generated by Django 4.2.3 on 2025-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20250617_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttemplate',
            name='category_new_fk',
        ),
        migrations.AddField(
            model_name='texttemplate',
            name='template_type',
            field=models.CharField(db_index=True, default='gutierrez', help_text='Тип шаблона: gutierrez, rossi и т.д.', max_length=32),
        ),
    ]
