# Generated by Django 4.2.3 on 2025-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_texttemplate_category_new_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttemplate',
            name='template_type',
            field=models.CharField(blank=True, choices=[('gutierrez', 'Gutierrez'), ('rossi', 'Rossi'), (None, 'Other')], help_text='Тип шаблона для разделения на разных страницах', max_length=20, null=True),
        ),
    ]
