# Generated by Django 4.2.3 on 2025-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_add_template_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
